name    'nigelkersten-win_desktop_shortcut'
version '0.0.4'
source 'git@github.com:nigelkersten/win_desktop_shortcut-module.git'
author 'nigelkersten'
license 'Apache License, Version 2.0'
summary 'A simple module demonstrating placing a shortcut on a Windows desktop.'
description 'This module places a shortcut to the PuppetLabs website on the desktop for all users on a Windows machine. It also demonstrates a simple fact to return Windows specific information as a fact.'
project_page 'https://github.com/nigelkersten/win_desktop_shortcut-module'
